spring.application.name=Student_Management_System
spring.datasource.url=jdbc:postgresql://localhost:5432/studentdb
spring.datasource.username=postgres
spring.datasource.password=21032006odom

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true